from agents import run_finalizer
from session_manager import session_manager
from memory.memory import AgentMemory

def finalizer_behaviour(llm, memory: AgentMemory, session_id: str, session_path: str):
        """Finalizes the session by running the finalizer agent.
        Args:
            llm: The language model to use for finalization.
            memory: An object that stores state, such as chat history and thinking steps.
            session_id: The ID of the session to finalize.
            session_path: The path to the session directory for file operations.
        Yields:
            str: The streamed tokens generated by the finalizer agent.
        """
        finalized_answer = ""

        for token in run_finalizer(llm, memory):
            finalized_answer += token
            yield token

        memory.chat_history_total.append({"role":"assistant","content":finalized_answer})

        memory.thinkingsteps.clear()
        
        print("Saved session with ID:", session_id)
        print("Session path:", session_path)
        print("Saved Memory:", memory.chat_history_total)

        # Save the session with the finalized memory
        session_manager.save_session(session_id=session_id, session_path=session_path, memory=memory)
